# Generated by Django 5.0.1 on 2024-02-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMS_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='first_name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='last',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last',
            new_name='last_name',
        ),
    ]
